export const ADD_CALENDAR = 'ADD_CALENDAR';
export const ADD_CALENDAR_SUCCESS = 'ADD_CALENDAR_SUCCESS';
export const ADD_CALENDAR_ERROR = 'ADD_CALENDAR_ERROR';

export const FETCH_CALENDAR = 'FETCH_CALENDAR';
export const FETCH_CALENDAR_SUCCESS = 'FETCH_CALENDAR_SUCCESS';
export const FETCH_CALENDAR_ERROR = 'FETCH_CALENDAR_ERROR';
export const CLEAR_ADD_CALENDAR = 'CLEAR_ADD_CALENDAR';
