export const ADD_CALENDAR = 'ADD_CALENDAR';
export const ADD_CALENDAR_SUCCESS = 'ADD_CALENDAR_SUCCESS';
export const ADD_CALENDAR_ERROR = 'ADD_CALENDAR_ERROR';

export const FETCH_CALENDAR = 'FETCH_CALENDAR';
export const FETCH_CALENDAR_SUCCESS = 'FETCH_CALENDAR_SUCCESS';
export const FETCH_CALENDAR_ERROR = 'FETCH_CALENDAR_ERROR';
export const CLEAR_ADD_CALENDAR = 'CLEAR_ADD_CALENDAR';

export const CONNECT_SOCIAL_ACCOUNT = 'CONNECT_SOCIAL_ACCOUNT';
export const CONNECT_SOCIAL_ACCOUNT_SUCCESS = 'CONNECT_SOCIAL_ACCOUNT_SUCCESS';
export const CONNECT_SOCIAL_ACCOUNT_FAILURE = 'CONNECT_SOCIAL_ACCOUNT_FAILURE';

export const INVITE_USER = 'INVITE_USER';
export const INVITE_USER_SUCCESS = 'INVITE_USER_SUCCESS';
export const INVITE_USER_FAILURE = 'INVITE_USER_FAILURE';

export const FETCH_CALENDAR_USER = 'FETCH_CALENDAR_USER';
export const FETCH_CALENDAR_USER_SUCCESS = 'FETCH_CALENDAR_USER_SUCCESS';
export const FETCH_CALENDAR_USER_FAILURE = 'FETCH_CALENDAR_USER_FAILURE';
